# Generated by Django 6.0.5 on 2026-06-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('ID_Alumno', models.AutoField(primary_key=True, serialize=False)),
                ('DNI', models.TextField(max_length=10)),
                ('Apellido', models.TextField(max_length=35)),
                ('Nombre', models.TextField(max_length=35)),
                ('Edad', models.IntegerField()),
                ('Calle', models.TextField(max_length=50)),
                ('Altura', models.IntegerField()),
            ],
        ),
    ]
